runtime: nodejs22
instance_class: F1
env: standard
entrypoint: npm start
automatic_scaling:
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.75
  max_instances: 2
env_variables:
  NODE_ENV: production
  DATABASE_URL: 'sm://client-information-db/DATABASE_URL'
  ccloud_sql_instances: client-information-db:europe-west1-b:client-db-instance
  CLOUD_SQL_CONNECTION_NAME: client-information-db:europe-west1-b:client-db-instance